import Head from 'next/head';
import 'animate.css'
import Layout from '../Layout';
import '../public/css/animate.css';
import '../styles/globals.css'
import { SessionProvider } from "next-auth/react";
import { wrapper } from '../redux/store';
import { useSession } from 'next-auth/react'

function MyApp({ Component, pageProps: { session, ...pageProps } }) {

  return (
    <div className="h-screen">
      <Head>
        <title>UCloud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="../styles/globals.css" rel="stylesheet" />
      </Head>

      <SessionProvider session={session}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </SessionProvider>
    </div>
  )
}



export default wrapper.withRedux(MyApp);

